# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_auto_20170622_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(related_name='users', to='book_app.Interest'),
        ),
    ]
